# TPM plugin manager
set -g @plugin 'tmux-plugins/tpm'

# manual save/restore sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'

# automatic periodic save + restore after reboot
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

# initialize TPM (MUST be last line)
run '~/.tmux/plugins/tpm/tpm'


# switch windows using Ctrl+Alt+Left/Right without prefix
bind -n C-M-Left previous-window
bind -n C-M-Right next-window

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


# ========================
# General Settings
# ========================
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour '#89b4fa'

# copy mode
setw -g mode-style 'fg=#1e1e2e,bg=#89b4fa'

# panes
set -g pane-border-style 'fg=#45475a'
set -g pane-active-border-style 'fg=#89b4fa'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=#cdd6f4,bg=#1e1e2e'

set -g status-left '#[fg=#1e1e2e,bg=#89b4fa,bold] #{mouse:?#[bg=#a6e3a1] 🖱 #[default]}#S #[fg=#89b4fa,bg=#1e1e2e,nobold]'
set -g status-left-length 40

set -g status-right '#[fg=#1e1e2e,bg=#a6e3a1] #H #[fg=#a6e3a1,bg=#1e1e2e]#[fg=#cdd6f4] %Y-%m-%d %H:%M '
set -g status-right-length 80

setw -g window-status-current-style 'fg=#1e1e2e,bg=#89b4fa'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-style 'fg=#a6adc8,bg=#1e1e2e'
setw -g window-status-format ' #I #[fg=#cdd6f4]#W #[fg=#a6adc8]#F '
setw -g window-status-bell-style 'fg=#1e1e2e,bg=#f38ba8,bold'

# toggle mouse on/off with prefix + Ctrl+m (Enter)
bind C-m set -g mouse

# messages
set -g message-style 'fg=#cdd6f4,bg=#45475a'
set -g message-command-style 'fg=#cdd6f4,bg=#45475a'
